#pragma once

// Error Fallback
#define IDR_ERROR_TEXTURE						"IDR_ERROR_TEXTURE"
#define IDR_ERROR_VERTICES 						"IDR_ERROR_VERTICES"
#define IDR_ERROR_INDICES						"IDR_ERROR_INDICES"
#define IDR_ERROR_VERTEX_SHADER					"IDR_ERROR_VERTEX_SHADER"
#define IDR_ERROR_FRAGMENT_SHADER				"IDR_ERROR_FRAGMENT_SHADER"

// PostProcess Shader
#define IDR_BLIT_VERTEX_SHADER					"IDR_BLIT_VERTEX_SHADER"
#define IDR_BLIT_FRAGMENT_SHADER				"IDR_BLIT_FRAGMENT_SHADER"
#define IDR_GAMMA_CORRECTION_VERTEX_SHADER		"IDR_GAMMA_CORRECTION_VERTEX_SHADER"
#define IDR_GAMMA_CORRECTION_FRAGMENT_SHADER	"IDR_GAMMA_CORRECTION_FRAGMENT_SHADER"
#define IDR_TONEMAPPING_VERTEX_SHADER			"IDR_TONEMAPPING_VERTEX_SHADER"
#define IDR_TONEMAPPING_FRAGMENT_SHADER			"IDR_TONEMAPPING_FRAGMENT_SHADER"

// Shader
#define IDR_DEFAULT_STATIC_VERTEX_SHADER		"IDR_DEFAULT_STATIC_VERTEX_SHADER"
#define IDR_DEFAULT_STATIC_FRAGMENT_SHADER		"IDR_DEFAULT_STATIC_FRAGMENT_SHADER"

// Shadow
#define IDR_SHADOW_STATIC_VERTEX_SHADER			"IDR_SHADOW_STATIC_VERTEX_SHADER"
#define IDR_SHADOW_STATIC_FRAGMENT_SHADER		"IDR_SHADOW_STATIC_FRAGMENT_SHADER"
#define IDR_SHADOW_SKINNED_VERTEX_SHADER		"IDR_SHADOW_SKINNED_VERTEX_SHADER"
#define IDR_SHADOW_SKINNED_FRAGMENT_SHADER		"IDR_SHADOW_SKINNED_FRAGMENT_SHADER"

// IBL
#define IDR_IBL_EQUIRECT_TO_CUBEMAP_VERTEX_SHADER		"IDR_IBL_EQUIRECT_TO_CUBEMAP_VERTEX_SHADER"
#define IDR_IBL_EQUIRECT_TO_CUBEMAP_FRAGMENT_SHADER		"IDR_IBL_EQUIRECT_TO_CUBEMAP_FRAGMENT_SHADER"
#define IDR_IBL_IRRADIANCE_CONVOLUTION_VERTEX_SHADER	"IDR_IBL_IRRADIANCE_CONVOLUTION_VERTEX_SHADER"
#define IDR_IBL_IRRADIANCE_CONVOLUTION_FRAGMENT_SHADER	"IDR_IBL_IRRADIANCE_CONVOLUTION_FRAGMENT_SHADER"
#define IDR_IBL_GGX_PREFILTER_VERTEX_SHADER				"IDR_IBL_GGX_PREFILTER_VERTEX_SHADER"
#define IDR_IBL_GGX_PREFILTER_FRAGMENT_SHADER			"IDR_IBL_GGX_PREFILTER_FRAGMENT_SHADER"
#define IDR_IBL_BRDF_LUT_GEN_VERTEX_SHADER				"IDR_IBL_BRDF_LUT_GEN_VERTEX_SHADER"
#define IDR_IBL_BRDF_LUT_GEN_FRAGMENT_SHADER			"IDR_IBL_BRDF_LUT_GEN_FRAGMENT_SHADER"
#define IDR_IBL_BRDF_LUT								"IDR_IBL_BRDF_LUT"
#define IDR_SKYBOX_HDR									"IDR_SKYBOX_HDR"

// SkyBox
#define IDR_SKYBOX_VERTEX_SHADER						"IDR_SKYBOX_VERTEX_SHADER"
#define IDR_SKYBOX_FRAGMENT_SHADER						"IDR_SKYBOX_FRAGMENT_SHADER"

// Fonts
#define IDR_FONT_FA_SOLID_900_TTF				"IDR_FONT_FA_SOLID_900_TTF"
#define IDR_FONT_SEGOEUI_TTF					"IDR_FONT_SEGOEUI_TTF"