#pragma once

// Error Fallback
#define IDR_ERROR_TEXTURE						"IDR_ERROR_TEXTURE"
#define IDR_ERROR_VERTICES 						"IDR_ERROR_VERTICES"
#define IDR_ERROR_INDICES						"IDR_ERROR_INDICES"
#define IDR_ERROR_VERTEX_SHADER					"IDR_ERROR_VERTEX_SHADER"
#define IDR_ERROR_FRAGMENT_SHADER				"IDR_ERROR_FRAGMENT_SHADER"

// PostProcess Shader
#define IDR_BLIT_VERTEX_SHADER					"IDR_BLIT_VERTEX_SHADER"
#define IDR_BLIT_FRAGMENT_SHADER				"IDR_BLIT_FRAGMENT_SHADER"
#define IDR_GAMMA_CORRECTION_VERTEX_SHADER		"IDR_GAMMA_CORRECTION_VERTEX_SHADER"
#define IDR_GAMMA_CORRECTION_FRAGMENT_SHADER	"IDR_GAMMA_CORRECTION_FRAGMENT_SHADER"

// BuildIn Asset
#define IDR_BUILDIN_DEFAULT_VERTEX_SHADER		"IDR_BUILDIN_DEFAULT_VERTEX_SHADER"
#define IDR_BUILDIN_DEFAULT_FRAGMENT_SHADER		"IDR_BUILDIN_DEFAULT_FRAGMENT_SHADER"
